services:
  db:
    image: postgres
    container_name: db-03
    env_file: .postgres.env
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: always
    networks:
      - exercicio-03

  app-python:
    build:
      context: ./apppython
      dockerfile: Dockerfile.dev
    container_name: app-python-03
    ports:
      - "8000:8000"
    volumes:
      - ./apppython:/app
    env_file:
      - ./apppython/.pythonapp.env.dev
    environment:
      - PYTHON_ENV=development
    depends_on:
      - db
    networks:
      - exercicio-03
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - exercicio-02

networks:
  exercicio-02:
    name: exercicio-02
    driver: bridge